# Generated by Django 3.1.1 on 2020-09-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answear',
            name='commentaries',
            field=models.ManyToManyField(blank=True, to='base.Commentary'),
        ),
        migrations.AlterField(
            model_name='answear',
            name='deslikes',
            field=models.ManyToManyField(blank=True, to='base.Deslike'),
        ),
        migrations.AlterField(
            model_name='answear',
            name='likes',
            field=models.ManyToManyField(blank=True, to='base.Like'),
        ),
        migrations.AlterField(
            model_name='answear',
            name='reports',
            field=models.ManyToManyField(blank=True, to='base.Report'),
        ),
        migrations.AlterField(
            model_name='book',
            name='commentaries',
            field=models.ManyToManyField(blank=True, to='base.Commentary'),
        ),
        migrations.AlterField(
            model_name='book',
            name='deslikes',
            field=models.ManyToManyField(blank=True, to='base.Deslike'),
        ),
        migrations.AlterField(
            model_name='book',
            name='likes',
            field=models.ManyToManyField(blank=True, to='base.Like'),
        ),
        migrations.AlterField(
            model_name='book',
            name='questions',
            field=models.ManyToManyField(blank=True, to='base.Question'),
        ),
        migrations.AlterField(
            model_name='book',
            name='reports',
            field=models.ManyToManyField(blank=True, to='base.Report'),
        ),
        migrations.AlterField(
            model_name='book',
            name='subject',
            field=models.ManyToManyField(blank=True, to='base.Subject'),
        ),
        migrations.AlterField(
            model_name='book',
            name='users',
            field=models.ManyToManyField(blank=True, to='base.UserPermission'),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='deslikes',
            field=models.ManyToManyField(blank=True, to='base.Deslike'),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='likes',
            field=models.ManyToManyField(blank=True, to='base.Like'),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='reports',
            field=models.ManyToManyField(blank=True, to='base.Report'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='reports',
            field=models.ManyToManyField(blank=True, to='base.Report'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='base.Subject'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answears',
            field=models.ManyToManyField(blank=True, to='base.Answear'),
        ),
        migrations.AlterField(
            model_name='question',
            name='commentaries',
            field=models.ManyToManyField(blank=True, to='base.Commentary'),
        ),
        migrations.AlterField(
            model_name='question',
            name='deslikes',
            field=models.ManyToManyField(blank=True, to='base.Deslike'),
        ),
        migrations.AlterField(
            model_name='question',
            name='likes',
            field=models.ManyToManyField(blank=True, to='base.Like'),
        ),
        migrations.AlterField(
            model_name='question',
            name='reports',
            field=models.ManyToManyField(blank=True, to='base.Report'),
        ),
        migrations.AlterField(
            model_name='question',
            name='users',
            field=models.ManyToManyField(blank=True, to='base.UserPermission'),
        ),
        migrations.AlterField(
            model_name='standarduser',
            name='addresses',
            field=models.ManyToManyField(blank=True, to='base.Address'),
        ),
        migrations.AlterField(
            model_name='standarduser',
            name='notifications',
            field=models.ManyToManyField(blank=True, to='base.Notification'),
        ),
        migrations.AlterField(
            model_name='standarduser',
            name='reports',
            field=models.ManyToManyField(blank=True, to='base.Report'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='reports',
            field=models.ManyToManyField(blank=True, to='base.Report'),
        ),
        migrations.AlterField(
            model_name='university',
            name='addresses',
            field=models.ManyToManyField(blank=True, to='base.Address'),
        ),
        migrations.AlterField(
            model_name='university',
            name='commentaries',
            field=models.ManyToManyField(blank=True, to='base.Commentary'),
        ),
        migrations.AlterField(
            model_name='university',
            name='deslikes',
            field=models.ManyToManyField(blank=True, to='base.Deslike'),
        ),
        migrations.AlterField(
            model_name='university',
            name='likes',
            field=models.ManyToManyField(blank=True, to='base.Like'),
        ),
        migrations.AlterField(
            model_name='university',
            name='reports',
            field=models.ManyToManyField(blank=True, to='base.Report'),
        ),
        migrations.AlterField(
            model_name='university',
            name='users',
            field=models.ManyToManyField(blank=True, to='base.UserPermission'),
        ),
    ]
