# Generated by Django 3.1.1 on 2020-09-28 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deslike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('answears', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.answear')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('answears', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.answear')),
            ],
        ),
        migrations.CreateModel(
            name='LikesDeslikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deslikes', models.ManyToManyField(blank=True, to='base.Deslike')),
                ('likes', models.ManyToManyField(blank=True, to='base.Like')),
                ('standarduser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.standarduser')),
            ],
        ),
        migrations.RemoveField(
            model_name='likes',
            name='answears',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='books',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='notifications',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='standarduser',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='universities',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='comments',
            new_name='commentary',
        ),
        migrations.RemoveField(
            model_name='book',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='book',
            name='userpermissions',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='userpermissions',
        ),
        migrations.RemoveField(
            model_name='question',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='question',
            name='userpermissions',
        ),
        migrations.RemoveField(
            model_name='university',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='university',
            name='userpermissions',
        ),
        migrations.AddField(
            model_name='commentary',
            name='answear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.answear'),
        ),
        migrations.AddField(
            model_name='commentary',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.book'),
        ),
        migrations.AddField(
            model_name='commentary',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.question'),
        ),
        migrations.AddField(
            model_name='commentary',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.university'),
        ),
        migrations.AddField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.exam'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='answear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.answear'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.book'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='commentary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.commentary'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.question'),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.university'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.subject'),
        ),
        migrations.DeleteModel(
            name='Deslikes',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
        migrations.AddField(
            model_name='like',
            name='books',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.book'),
        ),
        migrations.AddField(
            model_name='like',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.commentary'),
        ),
        migrations.AddField(
            model_name='like',
            name='notifications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.notification'),
        ),
        migrations.AddField(
            model_name='like',
            name='universities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.university'),
        ),
        migrations.AddField(
            model_name='deslike',
            name='books',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.book'),
        ),
        migrations.AddField(
            model_name='deslike',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.commentary'),
        ),
        migrations.AddField(
            model_name='deslike',
            name='notifications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.notification'),
        ),
        migrations.AddField(
            model_name='deslike',
            name='universities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.university'),
        ),
    ]
