# Generated by Django 3.1.1 on 2020-10-30 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeToApplyExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_to_apply', models.DateTimeField(blank=True, null=True)),
                ('date_to_finish', models.DateTimeField(blank=True, null=True)),
                ('exam', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.exam')),
            ],
        ),
    ]
