# Generated by Django 3.1.1 on 2020-11-07 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answear',
            name='standarduser',
        ),
        migrations.RemoveField(
            model_name='book',
            name='standarduser',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='standarduser',
        ),
        migrations.RemoveField(
            model_name='question',
            name='standarduser',
        ),
        migrations.RemoveField(
            model_name='timetoapplyexam',
            name='standarduser',
        ),
    ]
