# Generated by Django 3.1.1 on 2020-11-03 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_timetoapplyexam'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermissionExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('S', 'Student'), ('T', 'Teacher'), ('P', 'Poster'), ('O', 'Owner')], max_length=1)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.exam')),
                ('standarduser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.standarduser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
