# Generated by Django 3.1.1 on 2020-09-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20200921_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='discipline_name',
            field=models.CharField(default='zed', max_length=100),
            preserve_default=False,
        ),
    ]
