# Generated by Django 3.1.1 on 2020-11-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20201107_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
