# Generated by Django 3.1.1 on 2020-11-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_userpermissionexam'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='year',
            field=models.CharField(choices=[('21', '2021'), ('20', '2020'), ('19', '2019'), ('18', '2018'), ('17', '2017'), ('16', '2016'), ('15', '2015'), ('14', '2014'), ('13', '2013'), ('12', '2012'), ('11', '2011'), ('10', '2010'), ('9', '2009'), ('8', '2008'), ('7', '2007'), ('6', '2006'), ('5', '2005'), ('4', '2004'), ('3', '2003'), ('2', '2002'), ('1', '2001'), ('0', '2000')], default=20, max_length=2),
            preserve_default=False,
        ),
    ]
