# Generated by Django 3.1.1 on 2020-09-21 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200920_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='data_created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='data_created',
            new_name='date_created',
        ),
    ]
