# Generated by Django 3.1.1 on 2020-09-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_subject_discipline_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='right_answear',
            field=models.CharField(blank=True, choices=[('A', 'a'), ('B', 'b'), ('C', 'c'), ('D', 'd'), ('E', 'e')], max_length=1),
        ),
    ]
