# Generated by Django 3.1.1 on 2020-09-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20200922_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answear',
            field=models.CharField(default='isohfhi', max_length=10000),
            preserve_default=False,
        ),
    ]
