# Generated by Django 3.1.1 on 2020-11-06 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_question_difficult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='question',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='question',
            name='university_name',
        ),
        migrations.RemoveField(
            model_name='university',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='books',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.book'),
        ),
        migrations.AddField(
            model_name='question',
            name='exams',
            field=models.ManyToManyField(blank=True, to='base.Exam'),
        ),
        migrations.AddField(
            model_name='question',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.university'),
        ),
        migrations.AlterField(
            model_name='answear',
            name='reports',
            field=models.ManyToManyField(blank=True, null=True, to='base.Report'),
        ),
        migrations.AlterField(
            model_name='book',
            name='reports',
            field=models.ManyToManyField(blank=True, null=True, to='base.Report'),
        ),
        migrations.AlterField(
            model_name='commentaryanswear',
            name='reports',
            field=models.ManyToManyField(blank=True, null=True, to='base.Report'),
        ),
        migrations.AlterField(
            model_name='commentarybook',
            name='reports',
            field=models.ManyToManyField(blank=True, null=True, to='base.Report'),
        ),
        migrations.AlterField(
            model_name='commentaryquestion',
            name='reports',
            field=models.ManyToManyField(blank=True, null=True, to='base.Report'),
        ),
        migrations.AlterField(
            model_name='commentaryuniversity',
            name='reports',
            field=models.ManyToManyField(blank=True, null=True, to='base.Report'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='reports',
            field=models.ManyToManyField(blank=True, null=True, to='base.Report'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='reports',
            field=models.ManyToManyField(blank=True, null=True, to='base.Report'),
        ),
        migrations.AlterField(
            model_name='question',
            name='reports',
            field=models.ManyToManyField(blank=True, null=True, to='base.Report'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='reports',
            field=models.ManyToManyField(blank=True, null=True, to='base.Report'),
        ),
        migrations.AlterField(
            model_name='university',
            name='addresses',
            field=models.ManyToManyField(blank=True, null=True, to='base.Address'),
        ),
        migrations.AlterField(
            model_name='university',
            name='reports',
            field=models.ManyToManyField(blank=True, null=True, to='base.Report'),
        ),
    ]
