# Generated by Django 3.1.1 on 2020-09-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20200922_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='discipline',
        ),
        migrations.RemoveField(
            model_name='question',
            name='university',
        ),
        migrations.AddField(
            model_name='university',
            name='questions',
            field=models.ManyToManyField(blank=True, to='base.Question'),
        ),
    ]
