# Generated by Django 3.1.1 on 2020-11-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20201106_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answear',
            name='reports',
            field=models.ManyToManyField(blank=True, to='base.Report'),
        ),
        migrations.AlterField(
            model_name='book',
            name='reports',
            field=models.ManyToManyField(blank=True, to='base.Report'),
        ),
        migrations.AlterField(
            model_name='commentaryanswear',
            name='reports',
            field=models.ManyToManyField(blank=True, to='base.Report'),
        ),
        migrations.AlterField(
            model_name='commentarybook',
            name='reports',
            field=models.ManyToManyField(blank=True, to='base.Report'),
        ),
        migrations.AlterField(
            model_name='commentaryquestion',
            name='reports',
            field=models.ManyToManyField(blank=True, to='base.Report'),
        ),
        migrations.AlterField(
            model_name='commentaryuniversity',
            name='reports',
            field=models.ManyToManyField(blank=True, to='base.Report'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='reports',
            field=models.ManyToManyField(blank=True, to='base.Report'),
        ),
        migrations.AlterField(
            model_name='question',
            name='reports',
            field=models.ManyToManyField(blank=True, to='base.Report'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='reports',
            field=models.ManyToManyField(blank=True, to='base.Report'),
        ),
        migrations.AlterField(
            model_name='university',
            name='addresses',
            field=models.ManyToManyField(blank=True, to='base.Address'),
        ),
        migrations.AlterField(
            model_name='university',
            name='reports',
            field=models.ManyToManyField(blank=True, to='base.Report'),
        ),
    ]
