# Generated by Django 3.1.1 on 2020-11-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20201106_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='reports',
            field=models.ManyToManyField(blank=True, to='base.Report'),
        ),
    ]
