# Generated by Django 3.1.1 on 2020-09-23 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20200923_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standarduser',
            name='account_type',
        ),
    ]
