# Generated by Django 3.1.1 on 2020-09-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_standarduser_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
