# Generated by Django 3.1.1 on 2020-09-23 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20200923_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='commentaries',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='commentaries',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='commentaries',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='commentaries',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='commentaries',
            new_name='comments',
        ),
    ]
