# Generated by Django 3.1.1 on 2020-09-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20200923_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='standarduser',
            name='color',
            field=models.CharField(blank=True, choices=[('W', 'White'), ('B', 'Black'), ('G', 'Grey')], default='W', max_length=1, null=True),
        ),
    ]
