# Generated by Django 3.1.1 on 2020-09-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_standarduser_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='standarduser',
            name='education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
