# Generated by Django 3.1.1 on 2020-09-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_standarduser_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='answear',
            name='is_public',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='commentary',
            name='is_public',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_public',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='is_public',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_public',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
