# Generated by Django 3.1.1 on 2020-09-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20200925_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standarduser',
            name='birth',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
