# Generated by Django 3.1.1 on 2020-09-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20200925_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='standarduser',
            name='permissions',
            field=models.ManyToManyField(blank=True, null=True, to='base.UserPermission'),
        ),
    ]
