# Generated by Django 3.1.1 on 2020-09-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_standarduser_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standarduser',
            name='permissions',
        ),
        migrations.AddField(
            model_name='standarduser',
            name='questions',
            field=models.ManyToManyField(blank=True, null=True, to='base.Question'),
        ),
    ]
