# Generated by Django 3.1.1 on 2020-09-26 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20200925_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standarduser',
            name='questions',
        ),
    ]
