# Generated by Django 3.1.1 on 2020-09-26 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20200926_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deslikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='answear',
            old_name='standard_user',
            new_name='standarduser',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='users',
            new_name='userpermissions',
        ),
        migrations.RenameField(
            model_name='commentary',
            old_name='standard_user',
            new_name='standarduser',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='users',
            new_name='userpermissions',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='users',
            new_name='userpermissions',
        ),
        migrations.RenameField(
            model_name='requisition',
            old_name='standard_user',
            new_name='standarduser',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='users',
            new_name='userpermissions',
        ),
        migrations.RenameField(
            model_name='userpermission',
            old_name='standard_user',
            new_name='standarduser',
        ),
        migrations.RemoveField(
            model_name='answear',
            name='deslike_count',
        ),
        migrations.RemoveField(
            model_name='answear',
            name='deslikes',
        ),
        migrations.RemoveField(
            model_name='answear',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='answear',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='book',
            name='deslike_count',
        ),
        migrations.RemoveField(
            model_name='book',
            name='deslikes',
        ),
        migrations.RemoveField(
            model_name='book',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='book',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='commentary',
            name='deslike_count',
        ),
        migrations.RemoveField(
            model_name='commentary',
            name='deslikes',
        ),
        migrations.RemoveField(
            model_name='commentary',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='commentary',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='deslike_count',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='deslikes',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answears_count',
        ),
        migrations.RemoveField(
            model_name='question',
            name='deslike_count',
        ),
        migrations.RemoveField(
            model_name='question',
            name='deslikes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='question',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='title',
        ),
        migrations.RemoveField(
            model_name='standarduser',
            name='reports',
        ),
        migrations.RemoveField(
            model_name='university',
            name='deslike_count',
        ),
        migrations.RemoveField(
            model_name='university',
            name='deslikes',
        ),
        migrations.RemoveField(
            model_name='university',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='university',
            name='likes',
        ),
        migrations.AddField(
            model_name='report',
            name='standarduser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.standarduser'),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='about',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Deslike',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.AddField(
            model_name='likes',
            name='answears',
            field=models.ManyToManyField(blank=True, to='base.Answear'),
        ),
        migrations.AddField(
            model_name='likes',
            name='books',
            field=models.ManyToManyField(blank=True, to='base.Book'),
        ),
        migrations.AddField(
            model_name='likes',
            name='comments',
            field=models.ManyToManyField(blank=True, to='base.Commentary'),
        ),
        migrations.AddField(
            model_name='likes',
            name='notifications',
            field=models.ManyToManyField(blank=True, to='base.Notification'),
        ),
        migrations.AddField(
            model_name='likes',
            name='standarduser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.standarduser'),
        ),
        migrations.AddField(
            model_name='likes',
            name='universities',
            field=models.ManyToManyField(blank=True, to='base.University'),
        ),
        migrations.AddField(
            model_name='deslikes',
            name='answears',
            field=models.ManyToManyField(blank=True, to='base.Answear'),
        ),
        migrations.AddField(
            model_name='deslikes',
            name='books',
            field=models.ManyToManyField(blank=True, to='base.Book'),
        ),
        migrations.AddField(
            model_name='deslikes',
            name='comments',
            field=models.ManyToManyField(blank=True, to='base.Commentary'),
        ),
        migrations.AddField(
            model_name='deslikes',
            name='notifications',
            field=models.ManyToManyField(blank=True, to='base.Notification'),
        ),
        migrations.AddField(
            model_name='deslikes',
            name='standarduser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.standarduser'),
        ),
        migrations.AddField(
            model_name='deslikes',
            name='universities',
            field=models.ManyToManyField(blank=True, to='base.University'),
        ),
    ]
