# Generated by Django 3.1.1 on 2020-09-26 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20200926_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='standarduser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.standarduser'),
        ),
    ]
