# Generated by Django 3.1.1 on 2020-09-26 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20200926_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='standarduser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.standarduser'),
        ),
    ]
