from django.contrib import admin
from .models import *

admin.site.register(Commentary)
admin.site.register(Report)
admin.site.register(Like)
admin.site.register(Deslike)
admin.site.register(City)
admin.site.register(Address)
admin.site.register(StandardUser)
admin.site.register(UserPermission)
admin.site.register(University)
admin.site.register(Subject)
admin.site.register(Discipline)
admin.site.register(Answear)
admin.site.register(Question)
admin.site.register(Exam)
admin.site.register(Book)
admin.site.register(Notification)
admin.site.register(Requisition)
